### ISSUE TITLE
CLI allows connecting to photon SoftAP during `setup wifi`

### ISSUE THREAD

**Issue by m-mcgowan** [spark/particle-cli#135]
```
$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: Photon-JZ6B
? Should I try to auto-detect the wireless security type? No
? Security Type: WPA2
```

Then a pause of 2-3 seconds before

```
TypeError: Object false has no method 'indexOf'
    at /usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js:533:22
    at SerialTrigger.serialDataCallback (/usr/local/lib/node_modules/particle-cli/lib/SerialTrigger.js:31:4)
    at SerialPort.emit (events.js:117:20)
    at whenBored (/usr/local/lib/node_modules/particle-cli/lib/SerialBoredParser.js:9:12)
    at null._onTimeout (/usr/local/lib/node_modules/particle-cli/lib/SerialBoredParser.js:16:5)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

I know this is a corner-case, just creating the issue so we have it in the backlog.

**Comment by brycekahle** [comment]
Can you make sure you are running the latest version of the CLI? That stack trace doesn't seem to line up.

**Comment by m-mcgowan** [comment]
Updated the cli, now it doesn't crash. (I was on 1.8.2 before iirc, now 1.8.3) 

```
? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: Photon-PHCL
? Should I try to auto-detect the wireless security type? No
? Security Type: WPA2
? Wi-Fi Password: asdfjkl
! Something went wrong: Serial timed out
```
