### ISSUE TITLE
Login / logout broken

### ISSUE THREAD

**Issue by dbrgn** [spark/particle-cli#145]
With a fresh "npm -g install particle-cli" on Alpine Linux:

```
/ # particle login
Error loading command /usr/lib/node_modules/particle-cli/commands/CloudCommands.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
particle: Unknown command: "login"
```

```
/ # particle logout
Error loading command /usr/lib/node_modules/particle-cli/commands/CloudCommands.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
particle: Unknown command: "logout"
```

```
/ # particle setup
Error loading command /usr/lib/node_modules/particle-cli/commands/CloudCommands.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
Error loading command /usr/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Error relocating /usr/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-linux-x64/serialport.node: __strcpy_chk: symbol not found
                  _   _      _        _
 _ __   __ _ _ __| |_(_) ___| | ___  (_) ___
| '_ \ / _` | '__| __| |/ __| |/ _ \ | |/ _ \
| |_) | (_| | |  | |_| | (__| |  __/_| | (_) |
| .__/ \__,_|_|   \__|_|\___|_|\___(_)_|\___/
|_|                     https://particle.io/

> Setup is easy! Let's get started...
? Hello Stranger! This seems to be your first time here. What would you like to do? Login
> Let's get you logged in!
/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'login' of undefined
    at login (/usr/lib/node_modules/particle-cli/commands/SetupCommand/index.js:261:7)
    at PromptUI.completed (/usr/lib/node_modules/particle-cli/commands/SetupCommand/index.js:143:19)
    at PromptUI.onCompletion (/usr/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
```

I'm using npm 2.7.4 and node 0.12.2.

The same thing happened on my Arch Linux box with npm 3.3.4 and node 4.1.1.

**Comment by emilyrose** [comment]
@dbrgn this looks like a known issue with node-serialport's incompatibility with node 4.x, which is nearly resolved by the looks of it. In the mean time please see this thread on our community forums: http://community.particle.io/t/particle-cli-incompatible-with-node-4-x/15853

**Comment by dbrgn** [comment]
Thanks!
