### ISSUE TITLE
particle setup crash

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-cli#154]
```
 Here's what we're going to send to the Photon:

> Wi-Fi Network: XX
> Password: XX
> Security: WPA2

 Would you like to continue with the information shown above? Yes

> Obtaining device information...
```

-> and then I was dropped back to the shell with no errors, using latest version of source.

**Comment by dmiddlecamp** [comment]
I think I maybe typed "y." instead of just y, which might have crashed it.

**Comment by brycekahle** [comment]
Reproduced. Does not require `y.`.
```
/Users/bwkahle/git/particle-cli/node_modules/asn1/lib/ber/reader.js:102
      throw newInvalidAsn1Error('encoding too long');
      ^

InvalidAsn1Error: encoding too long
    at module.exports.newInvalidAsn1Error (/Users/bwkahle/git/particle-cli/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader.readLength (/Users/bwkahle/git/particle-cli/node_modules/asn1/lib/ber/reader.js:102:13)
    at Reader.readSequence (/Users/bwkahle/git/particle-cli/node_modules/asn1/lib/ber/reader.js:135:16)
    at Object.module.exports.publicImport (/Users/bwkahle/git/particle-cli/node_modules/node-rsa/src/formats/pkcs1.js:118:14)
    at Object.module.exports.detectAndImport (/Users/bwkahle/git/particle-cli/node_modules/node-rsa/src/formats/formats.js:64:48)
    at NodeRSA.module.exports.NodeRSA.importKey (/Users/bwkahle/git/particle-cli/node_modules/node-rsa/src/NodeRSA.js:179:22)
    at new NodeRSA (/Users/bwkahle/git/particle-cli/node_modules/node-rsa/src/NodeRSA.js:69:18)
    at SoftAPSetup.response (/Users/bwkahle/git/particle-cli/node_modules/softap-setup/index.js:92:22)
    at Socket.onData (/Users/bwkahle/git/particle-cli/node_modules/softap-setup/index.js:230:3)
    at emitOne (events.js:77:13)
```
