### ISSUE TITLE
Recent release of CLI throws errors when updating on Windows

### ISSUE THREAD

**Issue by pkourany** [spark/particle-cli#168]
The most recently released CLI fails to update or install on Windows systems that were updating just fine before this release.  The problem seems to be with systems that don't have Visual Studio 2013 Express installed.  Previous CLI versions worked with VS2010.  Replacing VS2010 with VS2013 fixed the problem, at least form me on Win 7x64.

**Comment by brycekahle** [comment]
Do you know which module was failing to install? Please also specify your versions of `node` and `npm`.

**Comment by pkourany** [comment]
Sorry for the lack of details.  I have nodejs 0.12.0, npm 2.5.1 and python 2.7.10.  I did not keep a copy of the error but it was a long red message.  Perhaps @Moors7 can add those details from the VM he created.

**Comment by cmsunu28** [comment]
Hey @Moors7 do you have any more info about this one? @brycekahle any more details we might need to investigate?

**Comment by brycekahle** [comment]
Definitely need more details. The ones I specified earlier should be a good start.

**Comment by timelf123** [comment]
I reproduced with the following
> Python 2.7.11
Node 5.1.1
NPM 3.3.12
Windows 10

I also needed to add git to the PATH or I had errors. Even after git was on the path I got:
```
C:\Users\Tim> npm install -g particle-cli
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  jacobrosenthal/node-pre-gyp-github#production resetting remote C:\Users\Tim\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jacobrosenthal-node-pre-gyp-github-git-production-00f1b2658a8ab0261b1b6e8aa994ae37 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
C:\Users\Tim\AppData\Roaming\npm\particle -> C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\bin\particle.js

> serialport@2.0.5 install C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport
> node-pre-gyp install --fallback-to-build4
...
```

Npm install errors: 
```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport\build\bindi
ng.sln]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Tim\\AppData\\Roaming\\npm\\node_modules\\particle-cli\\node_modules\\serialport\\build\\Release\\node-v47-win32-x64\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\Tim\\AppData\\Roaming\\npm\\node_modules\\particle-cli\\node_modules\\serialport\\build\\Release\\node-v47-win32-x64"
gyp ERR! cwd C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport\build\Release\node-v47-win32-x64\serialport.node --module_name=serialport --module_path=C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport\build\Release\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tim\\AppData\\Roaming\\npm\\node_modules\\particle-cli\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Tim\AppData\Roaming\npm\node_modules\particle-cli\node_modules\serialport
...
```

Solution:
Install [Visual Studio 2015 Community Edition](https://www.visualstudio.com/en-us/post-download-vs?sku=community)

**Comment by brycekahle** [comment]
@timelf123 Can you try version 1.9.0 of the CLI? `node-serialport` added some node 5.x builds in 2.0.6 so that should remove the need for Visual Studio.

**Comment by m-mcgowan** [comment]
Closing out. Recent versions update fine.
