### ISSUE TITLE
Error loading command Error: Cannot find module serialport.node

### ISSUE THREAD

**Issue by robertdolca** [spark/particle-cli#176]
`particle setup`

```
Error loading command /usr/local/lib/node_modules/particle-cli/commands/CloudCommands.js Error: Cannot find module '/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64/serialport.node'
Error loading command /usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.4/Release/node-v46-darwin-x64/serialport.node'
```

```
readline.js:924
            throw err;
            ^

TypeError: Cannot read property 'findDevices' of undefined
    at SetupCommand.findDevice (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:298:8)
    at accountStatus (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:155:3)
    at PromptUI.switchChoice [as completed] (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:120:4)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
```

**Comment by brycekahle** [comment]
Please install the latest version of `particle-cli` by using `npm install -g particle-cli`

**Comment by robertdolca** [comment]
I have tha last version. Done that.

**Comment by robertdolca** [comment]
Aparently there is a new one (fresh update I supose)

**Comment by brycekahle** [comment]
I noticed it was trying to use serialport v1.7.4. We updated to 2.0 on October 12th.

**Comment by nanodust** [comment]
I still see this. 

sudo npm install -g particle-cli

but I still get 

```
Error loading command /usr/local/n/versions/node/5.6.0/lib/node_modules/particle-
cli/commands/SerialCommand.js Error: Cannot find module 
'/usr/local/n/versions/node/5.6.0/lib/node_modules/particle-
cli/node_modules/serialport/build/Release/node-v46-darwin-x64/serialport.node
```

if I figure out the answer, I'll post back here. 

I'm completely new to particle (electron). 

(just trying to monitor serial port :)

I'm on Yosimite OSX 10.10.5
```
$ uname -a
Darwin C02LG0FWF1G3.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
```
fyi, I use macports node 
```
$ which node
/opt/local/bin/node
```
and I don't see any of that in this path.

I'm updating all macport dependencies. will try again.

**Comment by nanodust** [comment]
ok, after updating all port
```
sudo port selfupdate
sudo port upgrade outdated
```

then a little
```
sudo npm install -g particle-cli
```
we see
```
> serialport@2.1.0 install /opt/local/lib/node_modules/particle-cli/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/opt/local/lib/node_modules/particle-cli/node_modules/serialport/build/Release/serialport.node" is installed via remote
/opt/local/bin/particle -> /opt/local/lib/node_modules/particle-cli/bin/particle.js
```
yay

tho - not yet... 

```
$  particle serial monitor
Error loading command /usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v46-darwin-x64/serialport.node'
particle: Unknown command: "serial"
```

and even

```
$ particle list
Error loading command /usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module '/usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v46-darwin-x64/serialport.node'
XXXXX [370048000a51343334363138] (Electron) is online

hmm...

**Comment by nanodust** [comment]
ok - for some reason

only : 
```
/usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/node_modules/serialport/build/Release/node-v47-darwin-x64
```
exists, but particle CLI seems to want node-v46-darwin not 47

let's 
```
sudo npm remove -g particle-cli
sudo npm install -g particle-cli
```
nope, still wants 46

symlinking- a bad idea anyway... 
```
sudo ln -s node-v47-darwin-x64 node-v46-darwin-x64
```
also doesn't work:
```
Error loading command /usr/local/n/versions/node/5.6.0/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Module version mismatch. Expected 46, got 47.
```
this is a system - specific thing. but i'm not sure where this went wrong, but it's wrong. 
case in point - where did this come from ? 
```
/usr/local/n/versions/node/5.6.0/
```
I do not recall ever setting that up. 
 I'm going to remove it, and particle CLI, and just try again now that macports is updated.

**Comment by nanodust** [comment]
no. there is some dependency hell with 
```
 sudo npm install node-pre-gyp node-pre-gyp-github
```
works fine on it's own, but fails when it' s a part of 

```
sudo npm install -g particle-cli
```

this is now a different thread :) moving on....

**Comment by spr-lfeliu** [comment]
I had a module version mismatch error for SerialCommand.js after I upgraded to nodejs v6. Downgrading my node version to 4.4.4 and doing a clean install of particle-cli fixed the issue.

**Comment by kneuron** [comment]
I just had the same issue as @spr-lfeliu (Thanks!!), and solved it with his suggestion of downgrading to 4.4.4 and reinstalling particle-cli.

**Comment by ericboehs** [comment]
Does particle-cli still not support Node 6?

**Comment by monkbroc** [comment]
Yes, the CLI works with Node 6. If you are having issues it is most likely due to upgrading node and having some modules still compiled for the old version. If you know where the particle-cli package was installed you can force reinstalling it by deleting the files for the particle-clil package and the serialport dependency. This is the likely culprit of a weird loading errors.

**Comment by vielmetti** [comment]
I'm seeing the same error, and it went away when I manually clobbered the serialport dependency and did a fresh install.

**Comment by ericboehs** [comment]
Yeah. That seems to be the solution. Not a big deal.

**Comment by JSchaenzle** [comment]
Deleting node_modules and re-running `npm install` resolved this for me as well.
