### ISSUE TITLE
`particle udp send` throws error but should provide help

### ISSUE THREAD

**Issue by ScruffR** [spark/particle-cli#185]
The UDP command for CLI is not that helpful if you don't already know how to use it.

`particle help udp` does give you this rahter "unhelpful" and mildly confusing info
```text
$$$>particle help udp
NAME:
particle udp

DOES:
    helps repair devices, run patches, check Wi-Fi, and more!

    particle udp send     - Sends a UDP packet to the specified host and port
```
How does it help repair the device and run patches?

But most importantly: **HOW** does the `send` command need to be formatted?
If you don't do it right, you get this
```text
$$$>particle udp send <no matter how I put it here>
buffer.js:67
    throw new TypeError('must start with number, buffer, array or string');
          ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:67:11)
    at Object.extend.sendUdpPacket (C:\Users\Andy\AppData\Roaming\npm\node_modules\particle-cli\commands\UdpCommands.js:56:13)
    at Object.BaseCommand.runCommand (C:\Users\Andy\AppData\Roaming\npm\node_modules\particle-cli\commands\BaseCommand.js:108:17)
    at Object.Interpreter.runCommand (C:\Users\Andy\AppData\Roaming\npm\node_modules\particle-cli\lib\interpreter.js:93:13)
    at Object.Interpreter.handle (C:\Users\Andy\AppData\Roaming\npm\node_modules\particle-cli\lib\interpreter.js:55:18)
    at Object.<anonymous> (C:\Users\Andy\AppData\Roaming\npm\node_modules\particle-cli\bin\particle.js:20:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by kennethlimcp** [comment]
The UDP command was rarely mentioned/used and probably coded in by Dave for some testing during the initial use of CLI with the core. We can remove this command for now if it's causing confusion.

**Comment by ScruffR** [comment]
Nope, I'd rather keep it, but have it documented.
I'd even like to have it extended with a `particle udp monitor` feature ;-)

It would be a nice and easy way to test UDP client functionality.
