### ISSUE TITLE
“events.js:72  throw er; // Unhandled 'error' event” during ‘particle setup’ with Photon

### ISSUE THREAD

**Issue by SableRaf** [spark/particle-cli#235]
Note: I updated particle-cli and the firmware before running `particle setup`.

```
➜  ~  particle setup
                  _   _      _        _
 _ __   __ _ _ __| |_(_) ___| | ___  (_) ___
| '_ \ / _` | '__| __| |/ __| |/ _ \ | |/ _ \
| |_) | (_| | |  | |_| | (__| |  __/_| | (_) |
| .__/ \__,_|_|   \__|_|\___|_|\___(_)_|\___/
|_|                     https://particle.io/

> Setup is easy! Let's get started...
> It appears as though you are already logged in as groupes.raphael@gmail.com
? Would you like to log in with a different account? No

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue!
! PROTIP: Please make sure you are connected to the internet.

> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
! The Photon supports secure Wi-Fi setup. We'll try that first.

! PROTIP: Wireless setup of Photons works like a wizard!
! PROTIP: We will automagically change the Wi-Fi network to which your computer is connected.
! PROTIP: You will lose your connection to the internet periodically.

> No nearby Photons detected. Try the `particle help` command for more information.
? Would you like to wait and monitor for Photons entering setup mode? Yes
> Monitoring nearby Wi-Fi networks for Photons. This may take up to a minute.
? Found "Photon-P9D5". Would you like to perform setup on this one now? Yes

! PROTIP: You will need to know the password for your Wi-Fi network (if any) to proceed.
! PROTIP: You can press ctrl + C to quit setup at any time.


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by SableRaf** [comment]
Note: the same error is mentioned here (in a different context) but I don't know what to make of the answer. 

http://stackoverflow.com/questions/17749055/nodejs-throw-er-unhandled-error-event-events-js72-when-using-child-proc

**Comment by brycekahle** [comment]
What OS are you using?

**Comment by SableRaf** [comment]
OS X 10.9.5
