### ISSUE TITLE
Can't flash firmware.bin

### ISSUE THREAD

**Issue by straccio** [spark/particle-cli#252]
Good morning,
with latest release i can't flash the device from cloud. 
Here the log
`
particle flash ${device_id} build/PHOTON/firmware.bin 
/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/CloudCommands.js:975
			var alwaysIncludeThisFile = ((ext === '.bin') && (i === 0) && (filelist.length === 1));
			                                                               ^

ReferenceError: filelist is not defined
    at Object.extend._handleMultiFileArgs (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/CloudCommands.js:975:67)
    at Object.extend.flashDevice (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/CloudCommands.js:263:20)
    at Object.extend.flashCloud (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/FlashCommand.js:141:28)
    at Object.extend.flashSwitch (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/FlashCommand.js:133:29)
    at Object.BaseCommand.runCommand (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/commands/BaseCommand.js:108:17)
    at Object.Interpreter.runCommand (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/lib/interpreter.js:93:13)
    at Object.Interpreter.handle (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/lib/interpreter.js:55:18)
    at Object.<anonymous> (/Users/###/.nvm/versions/node/v5.10.1/lib/node_modules/particle-cli/bin/particle.js:20:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
`

And here the line changed correctly
`
var alwaysIncludeThisFile = ((ext === '.bin') && (i === 0) && (filenames.length === 1));
`

**Comment by monkbroc** [comment]
Thanks for the report. I am about to release a new version today with the fix.

**Comment by straccio** [comment]
Thanks to your great job!

**Comment by monkbroc** [comment]
We have a new release out! Please run `npm update -g particle-cli` (you may need`sudo` in front depending on your setup).
