### ISSUE TITLE
Error when trying to setup photon

### ISSUE THREAD

**Issue by weftech** [spark/particle-cli#294]
When I attempt to run paricle setup in particle-cli I get the following error.

```
readline.js:983
            throw err;
            ^

TypeError: Cannot read property 'findDevices' of undefined
    at SetupCommand.findDevice (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:293:8)
    at accountStatus (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:150:3)
    at module.exports.switchChoice [as completed] (/usr/local/lib/node_modules/particle-cli/commands/SetupCommand/index.js:115:4)
    at module.exports.PromptUI.onCompletion (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/rx-lite/rx.lite.js:1489:14)
```

**Comment by monkbroc** [comment]
Hi,

Could you please give us more information about your computer and how you installed the CLI? Also try running `node -v` to get the node version.

**Comment by weftech** [comment]
7.0.0

**Comment by weftech** [comment]
Get the same erroe with 6.9.1

**Comment by monkbroc** [comment]
What operating system do you use?

**Comment by weftech** [comment]
macOS Sierra Verison 10.12.1 Beta (16B2553a)

**Comment by monkbroc** [comment]
Colleague who have the latest macOS haven't seen this issue. The error occurs on the serialport module which is known to cause issues due to be a native module. If you upgrade Node or upgrade the OS it tends to stop loading properly. I don't have a much better answer than to try to reinstall node and the CLI and watch for messages related to the serialport module.

**Comment by weftech** [comment]
How odd I did a complete reinstall and that worked. Thanks!
