### ISSUE TITLE
Wifi scan not working

### ISSUE THREAD

**Issue by kennethlimcp** [spark/particle-cli#3]
I happened to have internet sharing via Wifi turned on for MBP and attempted a scan:
(ie. Wifi device not available for scan)

The user should be aware of this but this still should not threw an unknown error to the user.

```
KENMBP:~ kennethlimcp$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? Yes

se arrow keys)



/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'name' of undefined
    at Prompt.render (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/prompts/list.js:99:69)
    at Prompt.onSubmit (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/prompts/list.js:122:16)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1962:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1894:35)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5018:51)
```

**Comment by brycekahle** [comment]
Thanks for the bug report!
