### ISSUE TITLE
particle list is broken

### ISSUE THREAD

**Issue by enjrolas** [spark/particle-cli#352]
I'm getting an error when I try running particle list
At first, I updated to the latest particle-cli, and then to rule out an update issue, I uninstalled and reinstalled particle CLI, and I'm still getting the error.

Here's the full dump of the problem:
```
Alexs-MBP-2:firmware japhy$ particle list
▀ Retrieving devices.../usr/local/lib/node_modules/particle-cli/oldlib/ApiClient.js:267
				if (body.error) {
				        ^

TypeError: Cannot read property 'error' of undefined
    at Request._callback (/usr/local/lib/node_modules/particle-cli/oldlib/ApiClient.js:267:13)
    at Request.self.callback (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
Alexs-MBP-2:firmware japhy$ 

```

**Comment by enjrolas** [comment]
oh, for the record -- mac OS X 10.12.2

**Comment by kennethlimcp** [comment]
What is your:

- `node --version`
- `particle --version`

**Comment by enjrolas** [comment]
Alexs-MBP-2:firmware japhy$ node --version

v6.9.2

Alexs-MBP-2:firmware japhy$ particle --version

1.20.1

**Comment by enjrolas** [comment]
oh, sheeeee....
I was monkeying with my homebrew install and had wiped my installed
programs.  When I reinstalled openssl, it worked.  Sorry for the hassle

**Comment by m-mcgowan** [comment]
Thanks for reporting back, glad to hear you found out the cause! 👍
