### ISSUE TITLE
CLI exits when selecting from multiple devices to setup

### ISSUE THREAD

**Issue by brycekahle** [spark/particle-cli#47]
version 1.5.11

Ran `particle setup` with two photons connected. Failed right after I selected one of them when prompted.

```
> Setup is easy! Let's get started...
> It appears as though you are already logged in as bryce@particle.io
? Would you like to log in with a different account? No

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue!
! PROTIP: Please make sure you are connected to the internet.

> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
! The Photon supports secure Wi-Fi setup. We'll try that first.

! PROTIP: Wireless setup of Photons works like a wizard!
! PROTIP: We will automagically change the Wi-Fi network to which your computer is connected.
! PROTIP: You may lose your connection to the internet for a moment.

Potentially unhandled rejection [2] Serial timed out (WARNING: non-Error used)
? Multiple Photons detected nearby. Would you like to select one to setup now? Yes
? Please select which Photons you would like to setup at this time. Photon-B397


/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Object Photon-B397 has no method 'pop'
    at setup (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/commands/WirelessCommand/index.js:336:75)
    at PromptUI.multipleAnswers [as completed] (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/commands/WirelessCommand/index.js:245:16)
    at PromptUI.onCompletion (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/Users/bwkahle/.nvm/v0.10.38/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObse%
```

**Comment by jnm2** [comment]
We are having the exact same issue.

**Comment by brycekahle** [comment]
I just tried to reproduce this and could not. Closing, but please re-open if you experience it again with the current version.
