### ISSUE TITLE
[Photon] `particle monitor` not working

### ISSUE THREAD

**Issue by javier-rodas** [spark/particle-cli#60]
```
$ particle monitor 3a003000034XXXXXXXXXXXXX
Hit CTRL-C to stop!
polling server to see what devices are online, and what variables are available
Which variable did you want?
Potentially unhandled rejection [1] ReferenceError: foundCore is not defined
    at /usr/local/lib/node_modules/particle-cli/commands/VariableCommand.js:94:22
    at tryCatchReject (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/particle-cli/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

I have the latest ```particle-cli``` version:
```
$ particle --version
1.5.16
```

And I'm testing it over a Photon with a user-application on top of the ```develop firmware``` version 0.4.2.

**Comment by kennethlimcp** [comment]
@emilyrose i have a fix for this but the code is written some time back and we might want to consider some refactoring for the `particle monitor` command ;)

**Comment by gmoore** [comment]
Having the same problem. `particle monitor` throws that stack trace. `particle get [id] [var]` returns a blank line. OSX 10.10.3

```
$ particle --version
1.5.16
$ npm -v
2.11.2
$ node -v
v0.12.6
```

**Comment by gmoore** [comment]
Looks like we just need 

`foundCore = cores[i]`

inserted into line 92 of this file

https://github.com/spark/particle-cli/blob/master/commands/VariableCommand.js

I'm going to bed, so I can't do it right now. Might take a stab at it in the morning.

**Comment by emilyrose** [comment]
@gmoore I think you're right, although that will also cause a flood of "Which variable did you want?" if you don't specify the variable. This definitely needs to be refactored.

**Comment by kennethlimcp** [comment]
^^ mentioned above for refactoring :D
