### ISSUE TITLE
[Photon] `particle setup` crashes when entering an empty SSID

### ISSUE THREAD

**Issue by javier-rodas** [spark/particle-cli#62]
```
$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? No
? SSID: 
? Security Type: WPA2
? Wi-Fi Password: 
 
/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'ssid' of undefined
    at PromptUI.completed (/usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js:349:41)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
```

It make no sense to continue with an empty ```SSID``` nor an empty ```password``` (with a "secured" WPA2, WPA or WEP security type).

It also crashes when choosing an empty ```SSID``` with an ```Unsecured``` security type (without password).
```
$ particle setup wifi
? Should I scan for nearby Wi-Fi networks? No
? SSID: 
? Security Type: Unsecured
 
/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'ssid' of undefined
    at PromptUI.completed (/usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js:349:41)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/particle-cli/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
```

**Comment by emilyrose** [comment]
thanks for this report, @javier-rodas!

I've just merged #64 by @kennethlimcp to fix this. Thanks @kennethlimcp!

:smile_cat:
