### ISSUE TITLE
`list` command erroring out.

### ISSUE THREAD

**Issue by crenwick** [spark/particle-cli#72]
When I run `$ particle list` I get this output instead of a list of my devices:

```sh
* Retrieving device functions and variables.../usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:799
		error = error || body.error;
		                     ^
TypeError: Cannot read property 'error' of undefined
    at Object.ApiClient.hasBadToken (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:799:24)
    at Request._callback (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:363:10)
    at Request.self.callback (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Running v1.5.16, and I am logged in.

**Comment by emilyrose** [comment]
@crenwick,

Hey! Thanks for the report! It looks like you got some very nasty error output from having a bad token! I will definitely fix this error output to be more helpful. In the mean time it looks like you need to login again.

**Comment by crenwick** [comment]
Logging in and/or restarting did not resolve the issue. 



- Charles

**Comment by emilyrose** [comment]
@crenwick,

Please try navigating to ~/.particle/ and removing "access_token" from the file `particle.config.json`
Then try again and let me know what's up!

Thanks for your help!

**Comment by kennethlimcp** [comment]
@emilyrose this relates to a bigger issue here and the fix might not be to trivial IMO - https://github.com/spark/particle-cli/issues/69

From what i saw few days back, the checks in places are somewhat not working due to *promises* issue and so on..

**Comment by crenwick** [comment]
Tried the fix, @emilyrose. Unfortunately it didn't seem to help.

**Comment by kennethlimcp** [comment]
@crenwick i'm wondering what's your **nodeJS** version

**Comment by crenwick** [comment]
Node is v0.12.6. `particle config identify` reveals an access token and api.particle.io as the API.

**Comment by kennethlimcp** [comment]
Ok i'm not 100% but the nodeJS version *might* but causing some issues. I have uninstalled CLI and reinstalled but manage to login fine.

What happens with `particle login`?

**Comment by crenwick** [comment]
Anytime I login I get `> Successfully completed login!` but `list` still gives me the same error as above.

**Comment by kennethlimcp** [comment]
It looks like your version is not the same though. The line at 799 is different from what i see in the source code.

Can you do `npm uninstall -g particle-cli` and `npm install -g particle-cli` again?

**Comment by crenwick** [comment]
Just did another reinstall--same error exists, though the line numbers seem to be slightly different.

```sh
* Retrieving device functions and variables.../usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:799
		error = error || body.error;
		                     ^
TypeError: Cannot read property 'error' of undefined
    at Object.ApiClient.hasBadToken (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:799:24)
    at Request._callback (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:363:10)
    at Request.self.callback (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by kennethlimcp** [comment]
I wonder what happens if you roll back to a much older version.

**Comment by crenwick** [comment]
`$ particle list` on v1.5.0 gives me:

```sh
Error loading command /usr/local/lib/node_modules/particle-cli/commands/SerialCommand.js Error: Cannot find module 'node-wifiscanner'
Error loading command /usr/local/lib/node_modules/particle-cli/commands/WirelessCommand Error: Cannot find module 'node-wifiscanner'
Checking with the cloud...
* Retrieving device functions and variables.../usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:800
		error = error || body.error;
		                     ^
TypeError: Cannot read property 'error' of undefined
    at Object.ApiClient.hasBadToken (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:800:24)
    at Request._callback (/usr/local/lib/node_modules/particle-cli/lib/ApiClient.js:365:10)
    at Request.self.callback (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by kennethlimcp** [comment]
Can you download:

- https://github.com/spark/particle-cli/releases/tag/v1.5.16 
- cd in to the directory
- `mkdir node_modules`
- `npm install`
-  `node app.js particle login`
- `node app.js particle list`

**Comment by crenwick** [comment]
Hmm, for some reason I'm getting `park-CLI: Unknown command: "particle"` when I run `node app.js particle login`.

**Comment by kennethlimcp** [comment]
opps sorry. should just be the command without **particle**

**Comment by crenwick** [comment]
Yup--I got the original error output on `list` again...

**Comment by kennethlimcp** [comment]
Ok that's uber weird. Will have to look into it. Haven't heard of this since most of us as using the latest version. It might have to do with the nodeJS version

**Comment by crenwick** [comment]
Maybe related... I just ran `token list` and it returned 359,555 tokens.

Yikes!

**Comment by dmiddlecamp** [comment]
Heya @crenwick ,

  Can you email me at david@particle.io ?  I'm curious what email address / user account you're using with the CLI?

Thanks!
David

**Comment by crenwick** [comment]
Down to just a few tokens now on the account and the error is still exists.

**Comment by emilyrose** [comment]
@crenwick ack, this is frustrating!

I've not been able to reproduce this error, but I've made some changes to the way errors are handled so we can at least have a better idea of what's happening.

**Comment by emilyrose** [comment]
@crenwick,

could you try using curl to see if you're able to retrieve a list of devices?
```
curl -H "Authorization: Bearer <your access_token here>" https://api.particle.io/v1/devices
```

Does this output any errors? Same for:

```
curl -H "Authorization: Bearer <your access_token here>" https://api.particle.io/v1/webhooks
```

Thanks for hanging in there. We'll get it figured out :smile: 

Also, thanks to @brycekahle for the curl suggestion :+1:

**Comment by crenwick** [comment]
Hi Emily.
Running the curl command with `/devices` gives me an output of my devices, but with `/webhooks` only responds with an empty array.

At least there is now a command I can run to get the status / list of my devices. :+1:

**Comment by emilyrose** [comment]
@crenwick,

I've also published a new version with a slight revision to how errors are being handled. Try v1.5.19 and let me know if you still see any error output, thanks!

**Comment by crenwick** [comment]
1.5.19 fixes the issue. Thanks @emilyrose! And :+1: on the console output colors.

**Comment by emilyrose** [comment]
yay! I'm glad we got this figured out, thanks again for all your help, @crenwick.

I'm glad you noticed the colors, too. I thought you might like them.
