### ISSUE TITLE
[Windows10] "Particle Serial Wifi" Crashes

### ISSUE THREAD

**Issue by chobberoni** [spark/particle-cli#94]
pastebin link: http://pastebin.com/4BpMP2tr

```
? Should I scan for nearby Wi-Fi networks? (Y/n) y
? Should I scan for nearby Wi-Fi networks? Yes
? Select the Wi-Fi network with which you wish to connect your device: sparkhaus2.4
? Should I try to auto-detect the wireless security type? Yes
 
 
C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'indexOf' of undefined
    at Object.inquirer.prompt.when (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\commands\SerialCommand.js:353:59)
    at Object.utils.runAsync (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\lib\utils\utils.js:29:22)
    at C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\lib\ui\prompt.js:131:13
    at tryCatcher (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at setDisposable (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:1976:19)
    at C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:2449:21
    at tryCatcher (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at setDisposable (C:\Users\spark\AppData\Roaming\npm\node_modules\particle-cli\node_modules\inquirer\node_modules\rx\dist\rx.js:5233:36)

```

**Comment by brycekahle** [comment]
This was fixed with https://github.com/spark/particle-cli/commit/c6296b5a7d5b21fd22e9beb0d6a1bece9402209e
